[uwsgi]
# User running the app
uid = ocsbackend
gid = ocsbackend

# Django-related settings
project = ocsinventory_backend
base = /app/ocsinventory-backend
chdir = /app/ocsinventory-backend
virtualenv = /app/ocs-venv

# Django's wsgi file
module = ocsinventory_backend.wsgi:application

# process-related settings
master = true
processes = 5

# the socket (use the full path to avoid any problems)
socket = /var/run/ocsinventory-backend/ocsinventory-backend.sock
chmod-socket = 666
vacuum = true

# Log settings
logto = /dev/stdout